<script lang="ts">
  import { t, currentLanguage } from '$lib/i18n';
  import { selectedDataset, comparisonMode } from '$lib/stores';
  
  // Define the type for open sections as an array of strings
  let openSections = $state<string[]>([]);
  
  // State for the prompt modal
  let showPromptModal = $state(false);
  
  // Function to handle modal keyboard events
  function handleModalKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      showPromptModal = false;
    }
  }
</script>

<div class="info-card">
  <div class="info-header">
    <h2 class="info-title">{$t.analysis.title}</h2>
  </div>
  
  <p class="info-description">
    {$t.analysis.methodology} 
    <a href="https://islam.zmo.de/s/westafrica/" target="_blank" rel="noopener noreferrer" class="info-link">
      {#if $currentLanguage === 'en'}
        <em>Islam West Africa Collection</em> (IWAC)
      {:else}
        <em>Collection Islam Afrique de l'Ouest</em> (<em>Islam West Africa Collection</em>, IWAC)
      {/if}
    </a>, 
    {$currentLanguage === 'en' ? 'a collaborative and open-access digital database developed by' : 'une base de données numérique collaborative et en libre accès développée par'} 
    <a href="https://www.frederickmadore.com/" target="_blank" rel="noopener noreferrer" class="info-link">Frédérick Madore</a>. 
    {$currentLanguage === 'en' ? 'The results were generated by a large language model (LLM) guided by a prompt specifically designed for this task. Each article was analyzed according to three complementary dimensions, whose methodological details and limitations are presented below:' : 'Les résultats ont été générés par un grand modèle de langage (LLM) guidé par un prompt spécifiquement conçu pour cette tâche. Chaque article a été analysé selon trois dimensions complémentaires, dont les détails méthodologiques et les limites sont présentés ci-dessous :'}
  </p>
  
  <div class="accordion-container">
    <div class="accordion-item">
      <h3>
        <button 
          class="accordion-trigger" 
          data-state={openSections.includes('polarite') ? 'open' : 'closed'}
          onclick={() => openSections = openSections.includes('polarite') ? openSections.filter(s => s !== 'polarite') : [...openSections, 'polarite']}
        >
          <span class="accordion-trigger-text">{$t.analysis.polaritySection}</span>
          <span class="accordion-icon" data-state={openSections.includes('polarite') ? 'open' : 'closed'}>▼</span>
        </button>
      </h3>
      {#if openSections.includes('polarite')}
        <div class="accordion-panel">
          <p class="panel-description">{$t.analysis.polarityDescription}</p>
          <ul class="sentiment-list">
            <li><span class="badge sentiment-very-positive">{$t.sentiment.veryPositive}</span> <span class="sentiment-desc">— {$t.analysis.veryPositiveDesc}</span></li>
            <li><span class="badge sentiment-positive">{$t.sentiment.positive}</span> <span class="sentiment-desc">— {$t.analysis.positiveDesc}</span></li>
            <li><span class="badge sentiment-neutral">{$t.sentiment.neutral}</span> <span class="sentiment-desc">— {$t.analysis.neutralDesc}</span></li>
            <li><span class="badge sentiment-negative">{$t.sentiment.negative}</span> <span class="sentiment-desc">— {$t.analysis.negativeDesc}</span></li>
            <li><span class="badge sentiment-very-negative">{$t.sentiment.veryNegative}</span> <span class="sentiment-desc">— {$t.analysis.veryNegativeDesc}</span></li>
            <li><span class="badge sentiment-na">{$t.sentiment.notApplicable}</span> <span class="sentiment-desc">— {$t.analysis.notApplicableNote}</span></li>
          </ul>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3>
        <button 
          class="accordion-trigger" 
          data-state={openSections.includes('subjectivite') ? 'open' : 'closed'}
          onclick={() => openSections = openSections.includes('subjectivite') ? openSections.filter(s => s !== 'subjectivite') : [...openSections, 'subjectivite']}
        >
          <span class="accordion-trigger-text">{$t.analysis.subjectivitySection}</span>
          <span class="accordion-icon" data-state={openSections.includes('subjectivite') ? 'open' : 'closed'}>▼</span>
        </button>
      </h3>
      {#if openSections.includes('subjectivite')}
        <div class="accordion-panel">
          <p class="panel-description">{$t.analysis.subjectivityDescription}</p>
          <ul class="sentiment-list">
            <li><span class="badge subjectivity-1">1</span> <strong class="subjectivity-label">{$t.subjectivity.factual}</strong> <span class="sentiment-desc">— {$t.analysis.factualDesc}</span></li>
            <li><span class="badge subjectivity-2">2</span> <strong class="subjectivity-label">{$t.subjectivity.ratherFactual}</strong> <span class="sentiment-desc">— {$t.analysis.ratherFactualDesc}</span></li>
            <li><span class="badge subjectivity-3">3</span> <strong class="subjectivity-label">{$t.subjectivity.mixed}</strong> <span class="sentiment-desc">— {$t.analysis.mixedDesc}</span></li>
            <li><span class="badge subjectivity-4">4</span> <strong class="subjectivity-label">{$t.subjectivity.ratherSubjective}</strong> <span class="sentiment-desc">— {$t.analysis.ratherSubjectiveDesc}</span></li>
            <li><span class="badge subjectivity-5">5</span> <strong class="subjectivity-label">{$t.subjectivity.subjective}</strong> <span class="sentiment-desc">— {$t.analysis.subjectiveDesc}</span></li>
          </ul>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3>
        <button 
          class="accordion-trigger" 
          data-state={openSections.includes('centralite') ? 'open' : 'closed'}
          onclick={() => openSections = openSections.includes('centralite') ? openSections.filter(s => s !== 'centralite') : [...openSections, 'centralite']}
        >
          <span class="accordion-trigger-text">{$t.analysis.centralitySection}</span>
          <span class="accordion-icon" data-state={openSections.includes('centralite') ? 'open' : 'closed'}>▼</span>
        </button>
      </h3>
      {#if openSections.includes('centralite')}
        <div class="accordion-panel">
          <p class="panel-description">{$t.analysis.centralityDescription}</p>
          <ul class="sentiment-list">
            <li><span class="badge centrality-very-central">{$t.centrality.veryCentral}</span> <span class="sentiment-desc">— {$t.analysis.veryCentralDesc}</span></li>
            <li><span class="badge centrality-central">{$t.centrality.central}</span> <span class="sentiment-desc">— {$t.analysis.centralDesc}</span></li>
            <li><span class="badge centrality-secondary">{$t.centrality.secondary}</span> <span class="sentiment-desc">— {$t.analysis.secondaryDesc}</span></li>
            <li><span class="badge centrality-marginal">{$t.centrality.marginal}</span> <span class="sentiment-desc">— {$t.analysis.marginalDesc}</span></li>
            <li><span class="badge centrality-not-addressed">{$t.centrality.notAddressed}</span> <span class="sentiment-desc">— {$t.analysis.notAddressedDesc}</span></li>
          </ul>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3>
        <button 
          class="accordion-trigger" 
          data-state={openSections.includes('methodologie') ? 'open' : 'closed'}
          onclick={() => openSections = openSections.includes('methodologie') ? openSections.filter(s => s !== 'methodologie') : [...openSections, 'methodologie']}
        >
          <span class="accordion-trigger-text">{$t.analysis.methodologyAiModel}</span>
          <span class="accordion-icon" data-state={openSections.includes('methodologie') ? 'open' : 'closed'}>▼</span>
        </button>
      </h3>
      {#if openSections.includes('methodologie')}
        <div class="accordion-panel">
          <div class="methodology-content">
            <div class="methodology-section">
              <h4 class="section-title">{$t.analysis.modelUsed}</h4>
              {#if $comparisonMode}
                <p class="section-text">
                  {$currentLanguage === 'en' ? 'The analysis uses two large language models (LLMs) to provide comparative insights:' : 'L\'analyse utilise deux grands modèles de langage (LLM) pour fournir des insights comparatifs :'}
                </p>
                <div class="model-grid">
                  <div class="model-card">
                    <div class="model-header">
                      <span class="model-icon">🤖</span>
                      <span class="model-name">ChatGPT (GPT-5 mini)</span>
                    </div>
                    <p class="model-description">
                      {$currentLanguage === 'en' ? 'OpenAI\'s efficient model with a 400,000-token context window, released August 2025. Enhanced reasoning and cost-effectiveness.' : 'Modèle efficace d\'OpenAI avec une fenêtre de contexte de 400 000 tokens, publié en août 2025. Raisonnement amélioré et coût optimisé.'}
                    </p>
                    <p class="model-description">
                      {$currentLanguage === 'en' 
                        ? "GPT-5 mini is a faster, more cost-efficient version of GPT-5. It's great for well-defined tasks and precise prompts." 
                        : "GPT-5 mini est une version plus rapide et économique de GPT-5. Idéal pour des tâches bien définies et des invites précises."}
                    </p>
                    <a class="model-link" href="https://platform.openai.com/docs/models/gpt-5-mini" target="_blank" rel="noopener noreferrer">Docs →</a>
                  </div>
                  <div class="model-card">
                    <div class="model-header">
                      <span class="model-icon">✨</span>
                      <span class="model-name">Gemini 2.5 Flash</span>
                    </div>
                    <p class="model-description">
                      {$currentLanguage === 'en' ? 'Google\'s fast multimodal model optimized for diverse tasks with enhanced performance and efficiency.' : 'Modèle multimodal rapide de Google optimisé pour diverses tâches avec des performances et une efficacité améliorées.'}
                    </p>
                  </div>
                </div>
                <p class="section-note">
                  {$currentLanguage === 'en' ? 'Use the dataset picker in the header to switch between models or enable comparison mode to analyze differences in their outputs.' : 'Utilisez le sélecteur de jeu de données dans l\'en-tête pour basculer entre les modèles ou activer le mode comparaison pour analyser les différences dans leurs sorties.'}
                </p>
              {:else}
                <p class="section-text">
                  {$selectedDataset === 'chatgpt' 
                    ? ($currentLanguage === 'en' 
                      ? 'The analysis was performed using ' 
                      : 'L\'analyse a été réalisée avec ')
                    : ($currentLanguage === 'en' 
                      ? 'The analysis was performed using ' 
                      : 'L\'analyse a été réalisée avec ')}
                  
                  {#if $selectedDataset === 'chatgpt'}
                    <a href="https://platform.openai.com/docs/models/gpt-5-mini" target="_blank" rel="noopener noreferrer" class="model-badge chatgpt">
                      GPT-5 mini
                    </a>
                    {$currentLanguage === 'en' 
                      ? ', OpenAI\'s efficient model with a 400,000-token context window and enhanced reasoning capabilities, released in August 2025.' 
                      : ', le modèle efficace d\'OpenAI avec une fenêtre de contexte de 400 000 tokens et des capacités de raisonnement améliorées, publié en août 2025.'}
                    <span class="model-detail">{$currentLanguage === 'en' 
                      ? "GPT-5 mini is a faster, more cost-efficient version of GPT-5. It's great for well-defined tasks and precise prompts." 
                      : "GPT-5 mini est une version plus rapide et économique de GPT-5. Idéal pour des tâches bien définies et des invites précises."}</span>
                  {:else}
                    <a href="https://cloud.google.com/vertex-ai/generative-ai/docs/models/gemini/2-5-flash" target="_blank" rel="noopener noreferrer" class="model-badge gemini">
                      Gemini 2.5 Flash
                    </a>
                    {$currentLanguage === 'en' 
                      ? ', Google\'s fast multimodal model optimized for diverse tasks with enhanced performance and efficiency.' 
                      : ', le modèle multimodal rapide de Google optimisé pour diverses tâches avec des performances et une efficacité améliorées.'}
                  {/if}
                </p>
              {/if}
            </div>
            
            <div class="methodology-section">
              <h4 class="section-title">{$t.analysis.technicalConfiguration}</h4>
              <ul class="config-list">
                {#if $comparisonMode}
                  <li>{($currentLanguage === 'en' ? 'Gemini: ' : 'Gemini : ')}{$t.analysis.temperatureConfig}</li>
                {:else if $selectedDataset === 'gemini'}
                  <li>{$t.analysis.temperatureConfig}</li>
                {/if}
                <li>{$t.analysis.outputFormat}</li>
                <li>{$t.analysis.cacheSystem}</li>
                <li>{$t.analysis.errorHandling}</li>
                {#if $comparisonMode}
                  <li>{$currentLanguage === 'en' ? 'Parallel processing: Both models analyze the same articles independently' : 'Traitement parallèle : Les deux modèles analysent les mêmes articles de manière indépendante'}</li>
                  <li>{$currentLanguage === 'en' ? 'Discrepancy detection: Automatic identification of differences in sentiment analysis' : 'Détection des divergences : Identification automatique des différences dans l\'analyse de sentiment'}</li>
                {/if}
                <li>{$currentLanguage === 'en' ? 'API parameters: verbosity="low", reasoning.effort="low"' : 'Paramètres API : verbosity="low", reasoning.effort="low"'}</li>
              </ul>
            </div>
            
            <div class="methodology-section">
              <h4 class="section-title">{$t.analysis.analysisPrompt}</h4>
              <p class="section-text">
                {$comparisonMode 
                  ? ($currentLanguage === 'en' 
                    ? 'Both models use the same standardized prompt to ensure consistent analysis criteria across different AI systems:'
                    : 'Les deux modèles utilisent le même prompt standardisé pour assurer des critères d\'analyse cohérents entre les différents systèmes d\'IA :')
                  : $t.analysis.promptDescription}
              </p>
              <ul class="config-list">
                <li>{$t.analysis.promptFeature1}</li>
                <li>{$t.analysis.promptFeature2}</li>
                <li>{$t.analysis.promptFeature3}</li>
                <li>{$t.analysis.promptFeature4}</li>
                <li>{$t.analysis.promptFeature5}</li>
                {#if $comparisonMode}
                  <li>{$currentLanguage === 'en' ? 'Identical prompt ensures fair comparison between models' : 'Le prompt identique assure une comparaison équitable entre les modèles'}</li>
                {/if}
              </ul>
              <button 
                class="prompt-btn"
                onclick={() => showPromptModal = true}
              >
                {$t.analysis.viewFullPrompt}
              </button>
            </div>
          </div>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3>
        <button 
          class="accordion-trigger" 
          data-state={openSections.includes('limites') ? 'open' : 'closed'}
          onclick={() => openSections = openSections.includes('limites') ? openSections.filter(s => s !== 'limites') : [...openSections, 'limites']}
        >
          <span class="accordion-trigger-text">{$t.analysis.limitationsTitle}</span>
          <span class="accordion-icon" data-state={openSections.includes('limites') ? 'open' : 'closed'}>▼</span>
        </button>
      </h3>
      {#if openSections.includes('limites')}
        <div class="accordion-panel">
          <p class="panel-description">{$t.analysis.limitationsDescription}</p>
          {#if $comparisonMode}
            <div class="comparison-notice">
              <h4 class="section-title">
                {$currentLanguage === 'en' ? 'Comparison Mode Considerations' : 'Considérations du mode comparaison'}
              </h4>
              <ul class="config-list">
                <li>{$currentLanguage === 'en' ? 'Model differences may reflect varying training data, architectures, and optimization objectives rather than inherent accuracy' : 'Les différences entre modèles peuvent refléter des données d\'entraînement, des architectures et des objectifs d\'optimisation variables plutôt qu\'une précision inhérente'}</li>
                <li>{$currentLanguage === 'en' ? 'Neither model should be considered a ground truth; discrepancies highlight areas requiring human expert review' : 'Aucun modèle ne doit être considéré comme une vérité absolue ; les divergences soulignent les domaines nécessitant un examen d\'expert humain'}</li>
                <li>{$currentLanguage === 'en' ? 'Comparison results are most valuable when used to identify patterns and trends rather than definitive judgments' : 'Les résultats de comparaison sont plus utiles pour identifier des motifs et tendances que pour des jugements définitifs'}</li>
              </ul>
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </div>
</div>

<!-- Modal for displaying the complete prompt -->
{#if showPromptModal}
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <div 
    class="prompt-modal-backdrop" 
    role="dialog" 
    aria-modal="true" 
    aria-labelledby="prompt-modal-title"
    onclick={() => showPromptModal = false}
    onkeydown={handleModalKeydown}
    tabindex="-1"
  >
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <div 
      class="prompt-modal" 
      role="document"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
    >
      <div class="prompt-modal-header">
        <h3 id="prompt-modal-title" class="prompt-modal-title">{$currentLanguage === 'en' ? 'Complete Analysis Prompt' : 'Prompt d\'analyse complet'}</h3>
        <button 
          class="modal-close-btn" 
          onclick={() => showPromptModal = false}
          aria-label={$currentLanguage === 'en' ? 'Close modal' : 'Fermer la modal'}
          type="button"
        >
          ✕
        </button>
      </div>
      
      <div class="prompt-modal-body">
        {#if $currentLanguage === 'en'}
          <div class="translation-notice">
            <p>
              <strong>Note:</strong> This is a translation of the original French prompt used for the analysis. 
              The AI model received instructions in French as the corpus consists of French-language articles.
            </p>
          </div>
        {/if}
        
        <div class="prompt-code-container">
          <pre class="prompt-code">{$currentLanguage === 'en' ? 
            `You are an expert in sentiment analysis, specialized in studying representations of Islam and Muslims in the media, particularly in Francophone West Africa. Your task is to analyze the provided text from this specific angle and return a structured JSON analysis.

Your analysis must specifically evaluate how Islam and/or Muslims are depicted or represented in the article. Subjectivity and polarity should be judged in relation to this representation. If Islam and Muslims are only a marginal or irrelevant subject in the article, indicate this clearly.

For the following article text:
---
{article_text}
---

Please provide the following information in JSON format respecting the Pydantic SentimentAnalysisOutput schema:
{
  "centralite_islam_musulmans": "<Very central | Central | Secondary | Marginal | Not addressed>",
  "centralite_justification": "<Short justification (1 sentence) explaining the level of centrality of Islam/Muslims in the article>",
  "subjectivite_score": <score_from_1_to_5_or_null_if_not_addressed>,
  "subjectivite_justification": "<justification_in_1_2_sentences explaining why this subjectivity score was assigned regarding how the article treats Islam and/or Muslims, or 'Not applicable if the subject is not addressed'>",
  "polarite": "<Very positive | Positive | Neutral | Negative | Very negative | Not applicable>",
  "polarite_justification": "<justification_in_1_2_sentences explaining why this polarity was assigned regarding the portrayal of Islam and/or Muslims in the article, or 'Not applicable if the subject is not addressed'>"
}

Here are the scales to use:

Centrality of Islam and Muslims in the article:
- Very central: The article is mainly or entirely devoted to Islam and/or Muslims.
- Central: Islam and/or Muslims are one of the main subjects of the article.
- Secondary: Islam and/or Muslims are mentioned or discussed but do not constitute the main focus of the article.
- Marginal: Islam and/or Muslims are briefly mentioned anecdotally or peripherally.
- Not addressed: The article does not deal with Islam or Muslims at all.

Subjectivity (score from 1 to 5) – Evaluate the degree of objectivity/subjectivity of the article IN ITS WAY OF REPRESENTING Islam and/or Muslims (Assign 'null' if 'Not addressed' for centrality):
1: Very objective (reports verifiable facts about Islam/Muslims without expressing personal opinions or feelings about them, purely informative style on this theme).
2: Rather objective (mainly factual concerning Islam/Muslims, but may contain subtle traces of opinions or word choices suggesting a limited perspective on this theme).
3: Mixed (contains a balanced mix of facts and personal opinions/feelings concerning Islam/Muslims, or presents multiple viewpoints on this theme).
4: Rather subjective (clearly expresses opinions, feelings, or judgments about Islam/Muslims, even if based on some facts to support them).
5: Very subjective (heavily biased in its representation of Islam/Muslims, expresses intense opinions and emotions about them, with little or no objective presentation of facts, editorial or opinion piece style on this theme).

Polarity – Evaluate the general sentiment expressed IN THE ARTICLE TOWARDS Islam and/or Muslims, or concerning their representation (Assign 'Not applicable' if 'Not addressed' for centrality):
- Very positive: The portrayal of Islam/Muslims is extremely favorable, enthusiastic, laudatory.
- Positive: The portrayal of Islam/Muslims is favorable, optimistic.
- Neutral: No clear sentiment towards Islam/Muslims or balance between positive and negative aspects in their representation; factual tone without marked emotional charge towards them.
- Negative: The portrayal of Islam/Muslims is unfavorable, critical, pessimistic.
- Very negative: The portrayal of Islam/Muslims is extremely unfavorable, alarmist, very critical.

If centrality is "Not addressed", the "subjectivite_score" must be null, and "polarite", "subjectivite_justification", and "polarite_justification" must be "Not applicable". The JSON must always be valid.
For example, if "centralite_islam_musulmans" is "Not addressed":
{
  "centralite_islam_musulmans": "Not addressed",
  "centralite_justification": "The article mentions neither Islam nor Muslims.",
  "subjectivite_score": null,
  "subjectivite_justification": "Not applicable as the subject is not addressed.",
  "polarite": "Not applicable",
  "polarite_justification": "Not applicable as the subject is not addressed."
}

Make sure your response is only the requested structured JSON, without additional text or formatting before or after the JSON.` 
            : 
            `Vous êtes un expert en analyse de sentiments, spécialisé dans l'étude des représentations de l'islam et des musulmans dans les médias, notamment en Afrique de l'Ouest francophone. Votre tâche est d'analyser le texte fourni sous cet angle spécifique et de renvoyer une analyse structurée en JSON.

Votre analyse doit spécifiquement évaluer comment l'islam et/ou les musulmans sont dépeints ou représentés dans l'article. La subjectivité et la polarité doivent être jugées par rapport à cette représentation. Si l'islam et les musulmans ne sont qu'un sujet marginal ou non pertinent dans l'article, indiquez-le clairement.

Pour le texte de l'article suivant :
---
{article_text}
---

Veuillez fournir les informations suivantes au format JSON respectant le schéma Pydantic SentimentAnalysisOutput:
{
  "centralite_islam_musulmans": "<Très central | Central | Secondaire | Marginal | Non abordé>",
  "centralite_justification": "<Courte justification (1 phrase) expliquant le niveau de centralité de l'islam/des musulmans dans l'article>",
  "subjectivite_score": <score_de_1_a_5_ou_null_si_non_aborde>,
  "subjectivite_justification": "<justification_en_1_2_phrases expliquant pourquoi ce score de subjectivité a été attribué concernant la manière dont l'article traite de l'islam et/ou des musulmans, ou 'Non applicable si le sujet n'est pas abordé'>",
  "polarite": "<Très positif | Positif | Neutre | Négatif | Très négatif | Non applicable>",
  "polarite_justification": "<justification_en_1_2_phrases expliquant pourquoi cette polarité a été attribuée en ce qui concerne le portrait de l'islam et/ou des musulmans dans l'article, ou 'Non applicable si le sujet n'est pas abordé'>"
}

Voici les barèmes à utiliser :

Centralité de l'islam et des musulmans dans l'article :
- Très central : L'article est principalement ou entièrement consacré à l'islam et/ou aux musulmans.
- Central : L'islam et/ou les musulmans sont un des sujets principaux de l'article.
- Secondaire : L'islam et/ou les musulmans sont mentionnés ou discutés, mais ne constituent pas le focus principal de l'article.
- Marginal : L'islam et/ou les musulmans sont brièvement mentionnés de manière anecdotique ou périphérique.
- Non abordé : L'article ne traite pas du tout de l'islam ou des musulmans.

Subjectivité (note de 1 à 5) – Évaluez le degré d'objectivité/subjectivité de l'article DANS SA MANIÈRE DE REPRÉSENTER l'islam et/ou les musulmans (Attribuez 'null' si 'Non abordé' pour la centralité) :
1 : Très objectif (rapporte des faits vérifiables sur l'islam/les musulmans sans exprimer d'opinions ou de sentiments personnels à leur sujet, style purement informatif sur ce thème).
2 : Plutôt objectif (principalement factuel concernant l'islam/les musulmans, mais peut contenir des traces subtiles d'opinions ou des choix de mots suggérant une perspective limitée sur ce thème).
3 : Mixte (contient un mélange équilibré de faits et d'opinions/sentiments personnels concernant l'islam/les musulmans, ou présente plusieurs points de vue sur ce thème).
4 : Plutôt subjectif (exprime clairement des opinions, des sentiments ou des jugements sur l'islam/les musulmans, même s'il s'appuie sur certains faits pour les étayer).
5 : Très subjectif (fortement biaisé dans sa représentation de l'islam/des musulmans, exprime des opinions et des émotions intenses à leur sujet, avec peu ou pas de présentation objective des faits, style éditorial ou billet d'humeur sur ce thème).

Polarité – Évaluez le sentiment général exprimé DANS L'ARTICLE ENVERS l'islam et/ou les musulmans, ou concernant leur représentation (Attribuez 'Non applicable' si 'Non abordé' pour la centralité) :
- Très positif : Le portrait de l'islam/des musulmans est extrêmement favorable, enthousiaste, élogieux.
- Positif : Le portrait de l'islam/des musulmans est favorable, optimiste.
- Neutre : Pas de sentiment clair envers l'islam/des musulmans ou équilibre entre aspects positifs et négatifs dans leur représentation ; ton factuel sans charge émotionnelle marquée à leur égard.
- Négatif : Le portrait de l'islam/des musulmans est défavorable, critique, pessimiste.
- Très négatif : Le portrait de l'islam/des musulmans est extrêmement défavorable, alarmiste, très critique.

Si la centralité est "Non abordé", le "subjectivite_score" doit être null, et "polarite", "subjectivite_justification", et "polarite_justification" doivent être "Non applicable". Le JSON doit toujours être valide.
Par exemple, si "centralite_islam_musulmans" est "Non abordé":
{
  "centralite_islam_musulmans": "Non abordé",
  "centralite_justification": "L'article ne mentionne ni l'islam ni les musulmans.",
  "subjectivite_score": null,
  "subjectivite_justification": "Non applicable car le sujet n'est pas abordé.",
  "polarite": "Non applicable",
  "polarite_justification": "Non applicable car le sujet n'est pas abordé."
}

Assurez-vous que votre réponse est uniquement le JSON structuré demandé, sans texte ou formatage supplémentaire avant ou après le JSON.`}</pre>
        </div>
      </div>
      
      <div class="prompt-modal-footer">
        <button 
          class="close-btn" 
          onclick={() => showPromptModal = false}
          type="button"
        >
          {$t.common.close}
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  /* ==========================================================================
     INFO CARD - Main Container
     ========================================================================== */
  .info-card {
    background: color-mix(in oklab, var(--color-surface-900) 85%, transparent);
    backdrop-filter: blur(var(--glass-blur-md));
    border: 1px solid color-mix(in oklab, var(--color-surface-50) 10%, transparent);
    border-radius: 1rem;
    padding: 1.25rem;
    box-shadow: 
      0 4px 24px color-mix(in oklab, black 10%, transparent),
      inset 0 1px 0 color-mix(in oklab, var(--color-surface-50) 6%, transparent);
  }

  .info-header {
    margin-bottom: 1rem;
  }

  .info-title {
    font-size: 1.25rem;
    font-weight: 700;
    background: linear-gradient(135deg, var(--color-primary-400), var(--color-secondary-400));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    margin: 0;
  }

  .info-description {
    color: color-mix(in oklab, var(--color-surface-50) 85%, transparent);
    line-height: 1.7;
    font-size: 0.9375rem;
    margin-bottom: 1.25rem;
  }

  .info-link {
    color: var(--color-primary-400);
    text-decoration: underline;
    text-underline-offset: 2px;
    transition: color var(--timing-fast) var(--easing-default);
  }

  .info-link:hover {
    color: var(--color-primary-300);
  }

  /* ==========================================================================
     ACCORDION
     ========================================================================== */
  .accordion-container {
    display: flex;
    flex-direction: column;
    gap: 0;
    background: color-mix(in oklab, var(--color-surface-950) 60%, transparent);
    backdrop-filter: blur(var(--glass-blur-sm));
    border: 1px solid color-mix(in oklab, var(--color-surface-50) 8%, transparent);
    border-radius: 0.875rem;
    overflow: hidden;
  }

  .accordion-item {
    border-bottom: 1px solid color-mix(in oklab, var(--color-surface-50) 8%, transparent);
  }

  .accordion-item:last-child {
    border-bottom: none;
  }

  .accordion-trigger {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.875rem 1rem;
    background: color-mix(in oklab, var(--color-surface-50) 3%, transparent);
    border: none;
    color: var(--color-surface-50);
    font-size: 0.9375rem;
    font-weight: 600;
    cursor: pointer;
    transition: all var(--timing-fast) var(--easing-default);
    text-align: left;
  }

  .accordion-trigger:hover {
    background: color-mix(in oklab, var(--color-surface-50) 6%, transparent);
  }

  .accordion-trigger[data-state="open"] {
    background: color-mix(in oklab, var(--color-primary-500) 10%, transparent);
    border-left: 3px solid var(--color-primary-500);
  }

  .accordion-trigger-text {
    flex: 1;
  }

  .accordion-icon {
    font-size: 0.75rem;
    color: color-mix(in oklab, var(--color-surface-50) 60%, transparent);
    transition: transform var(--timing-fast) var(--easing-default);
  }

  .accordion-icon[data-state="open"] {
    transform: rotate(180deg);
    color: var(--color-primary-400);
  }

  .accordion-panel {
    padding: 1rem 1.25rem;
    background: color-mix(in oklab, var(--color-surface-950) 80%, transparent);
    animation: slideDown 0.2s var(--easing-default);
  }

  @keyframes slideDown {
    from {
      opacity: 0;
      transform: translateY(-8px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  .panel-description {
    color: color-mix(in oklab, var(--color-surface-50) 80%, transparent);
    font-size: 0.875rem;
    line-height: 1.6;
    margin-bottom: 1rem;
  }

  /* ==========================================================================
     SENTIMENT LISTS & BADGES
     ========================================================================== */
  .sentiment-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 0.625rem;
  }

  .sentiment-list li {
    display: flex;
    align-items: flex-start;
    gap: 0.625rem;
    font-size: 0.875rem;
    line-height: 1.5;
  }

  .sentiment-desc {
    color: color-mix(in oklab, var(--color-surface-50) 70%, transparent);
  }

  .subjectivity-label {
    color: var(--color-surface-50);
    font-weight: 500;
  }

  /* Badges use global classes from app.postcss:
     .sentiment-very-positive, .sentiment-positive, etc.
     .subjectivity-1 through .subjectivity-5
     .centrality-very-central, .centrality-central, etc. */

  /* ==========================================================================
     METHODOLOGY SECTION
     ========================================================================== */
  .methodology-content {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .methodology-section {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .section-title {
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--color-surface-50);
    margin: 0;
  }

  .section-text {
    color: color-mix(in oklab, var(--color-surface-50) 80%, transparent);
    font-size: 0.875rem;
    line-height: 1.6;
    margin: 0;
  }

  .section-note {
    color: color-mix(in oklab, var(--color-surface-50) 60%, transparent);
    font-size: 0.8125rem;
    font-style: italic;
    margin: 0;
  }

  .config-list {
    list-style: disc;
    padding-left: 1.25rem;
    margin: 0;
    color: color-mix(in oklab, var(--color-surface-50) 75%, transparent);
    font-size: 0.8125rem;
    line-height: 1.6;
  }

  .config-list li {
    margin-bottom: 0.25rem;
  }

  /* ==========================================================================
     MODEL CARDS (Comparison Mode)
     ========================================================================== */
  .model-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 0.875rem;
    margin-top: 0.5rem;
  }

  @media (max-width: 640px) {
    .model-grid {
      grid-template-columns: 1fr;
    }
  }

  .model-card {
    background: color-mix(in oklab, var(--color-surface-900) 60%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-surface-50) 10%, transparent);
    border-radius: 0.75rem;
    padding: 1rem;
    transition: all var(--timing-fast) var(--easing-default);
  }

  .model-card:hover {
    background: color-mix(in oklab, var(--color-surface-900) 70%, transparent);
    border-color: color-mix(in oklab, var(--color-surface-50) 15%, transparent);
    transform: translateY(-2px);
    box-shadow: 0 4px 12px color-mix(in oklab, black 15%, transparent);
  }

  .model-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
  }

  .model-icon {
    font-size: 1.25rem;
  }

  .model-name {
    font-weight: 600;
    font-size: 0.875rem;
    color: var(--color-surface-50);
  }

  .model-description {
    font-size: 0.75rem;
    color: color-mix(in oklab, var(--color-surface-50) 65%, transparent);
    line-height: 1.5;
    margin: 0 0 0.5rem 0;
  }

  .model-link {
    font-size: 0.75rem;
    color: var(--color-primary-400);
    text-decoration: none;
    transition: color var(--timing-fast) var(--easing-default);
  }

  .model-link:hover {
    color: var(--color-primary-300);
  }

  /* Model badges for single model view */
  .model-badge {
    display: inline-flex;
    align-items: center;
    padding: 0.25rem 0.625rem;
    font-size: 0.8125rem;
    font-weight: 600;
    border-radius: 0.375rem;
    text-decoration: none;
    transition: all var(--timing-fast) var(--easing-default);
  }

  .model-badge.chatgpt {
    background: color-mix(in oklab, var(--color-primary-500) 20%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-primary-500) 30%, transparent);
    color: var(--color-primary-300);
  }

  .model-badge.chatgpt:hover {
    background: color-mix(in oklab, var(--color-primary-500) 30%, transparent);
  }

  .model-badge.gemini {
    background: color-mix(in oklab, var(--color-secondary-500) 20%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-secondary-500) 30%, transparent);
    color: var(--color-secondary-300);
  }

  .model-badge.gemini:hover {
    background: color-mix(in oklab, var(--color-secondary-500) 30%, transparent);
  }

  .model-detail {
    display: block;
    margin-top: 0.5rem;
    font-size: 0.8125rem;
    color: color-mix(in oklab, var(--color-surface-50) 60%, transparent);
    font-style: italic;
  }

  /* ==========================================================================
     PROMPT BUTTON
     ========================================================================== */
  .prompt-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem 1rem;
    margin-top: 0.75rem;
    font-size: 0.8125rem;
    font-weight: 500;
    background: color-mix(in oklab, var(--color-primary-500) 15%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-primary-500) 25%, transparent);
    border-radius: 0.5rem;
    color: var(--color-primary-300);
    cursor: pointer;
    transition: all var(--timing-fast) var(--easing-default);
  }

  .prompt-btn:hover {
    background: color-mix(in oklab, var(--color-primary-500) 25%, transparent);
    border-color: color-mix(in oklab, var(--color-primary-500) 40%, transparent);
    transform: translateY(-1px);
  }

  /* ==========================================================================
     COMPARISON NOTICE
     ========================================================================== */
  .comparison-notice {
    margin-top: 1rem;
    padding: 1rem;
    background: color-mix(in oklab, var(--color-warning-500) 10%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-warning-500) 25%, transparent);
    border-radius: 0.625rem;
  }

  .comparison-notice .section-title {
    color: var(--color-warning-300);
    margin-bottom: 0.5rem;
  }

  .comparison-notice .config-list {
    color: color-mix(in oklab, var(--color-surface-50) 70%, transparent);
  }

  /* ==========================================================================
     PROMPT MODAL
     ========================================================================== */
  .prompt-modal-backdrop {
    position: fixed;
    inset: 0;
    z-index: 1000;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 1rem;
    background: color-mix(in oklab, var(--color-surface-950) 85%, transparent);
    backdrop-filter: blur(var(--glass-blur-sm));
    animation: fadeIn 0.2s var(--easing-default);
  }

  @keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }

  .prompt-modal {
    width: 100%;
    max-width: 850px;
    max-height: 90vh;
    display: flex;
    flex-direction: column;
    background: color-mix(in oklab, var(--color-surface-900) 95%, transparent);
    backdrop-filter: blur(var(--glass-blur-lg));
    border: 1px solid color-mix(in oklab, var(--color-surface-50) 12%, transparent);
    border-radius: 1rem;
    box-shadow: 
      0 16px 64px color-mix(in oklab, black 30%, transparent),
      0 0 40px color-mix(in oklab, var(--color-primary-500) 10%, transparent);
    animation: scaleIn 0.25s var(--easing-default);
    overflow: hidden;
  }

  @keyframes scaleIn {
    from {
      opacity: 0;
      transform: scale(0.95) translateY(10px);
    }
    to {
      opacity: 1;
      transform: scale(1) translateY(0);
    }
  }

  .prompt-modal::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 2px;
    background: linear-gradient(90deg, 
      transparent, 
      var(--color-primary-500), 
      var(--color-secondary-500), 
      transparent
    );
    opacity: 0.6;
  }

  .prompt-modal-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.25rem 1.5rem;
    border-bottom: 1px solid color-mix(in oklab, var(--color-surface-50) 10%, transparent);
    background: color-mix(in oklab, var(--color-surface-50) 3%, transparent);
  }

  .prompt-modal-title {
    font-size: 1.125rem;
    font-weight: 600;
    color: var(--color-surface-50);
    margin: 0;
  }

  .modal-close-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 2rem;
    height: 2rem;
    background: color-mix(in oklab, var(--color-surface-50) 8%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-surface-50) 12%, transparent);
    border-radius: 0.5rem;
    color: color-mix(in oklab, var(--color-surface-50) 80%, transparent);
    font-size: 1rem;
    cursor: pointer;
    transition: all var(--timing-fast) var(--easing-default);
  }

  .modal-close-btn:hover {
    background: color-mix(in oklab, var(--color-surface-50) 15%, transparent);
    border-color: color-mix(in oklab, var(--color-surface-50) 20%, transparent);
    color: var(--color-surface-50);
    transform: translateY(-1px);
  }

  .prompt-modal-body {
    flex: 1;
    overflow-y: auto;
    padding: 1.5rem;
  }

  .translation-notice {
    padding: 0.875rem 1rem;
    margin-bottom: 1rem;
    background: color-mix(in oklab, var(--color-warning-500) 12%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-warning-500) 25%, transparent);
    border-radius: 0.625rem;
  }

  .translation-notice p {
    color: var(--color-warning-300);
    font-size: 0.8125rem;
    line-height: 1.5;
    margin: 0;
  }

  .prompt-code-container {
    background: color-mix(in oklab, var(--color-surface-950) 80%, transparent);
    border: 1px solid color-mix(in oklab, var(--color-surface-50) 8%, transparent);
    border-radius: 0.625rem;
    padding: 1rem;
    overflow-x: auto;
  }

  .prompt-code {
    font-family: 'JetBrains Mono', 'Fira Code', 'Courier New', monospace;
    font-size: 0.8125rem;
    line-height: 1.6;
    color: color-mix(in oklab, var(--color-surface-50) 85%, transparent);
    white-space: pre-wrap;
    word-wrap: break-word;
    margin: 0;
  }

  .prompt-modal-footer {
    display: flex;
    justify-content: flex-end;
    padding: 1rem 1.5rem;
    border-top: 1px solid color-mix(in oklab, var(--color-surface-50) 10%, transparent);
    background: color-mix(in oklab, var(--color-surface-50) 2%, transparent);
  }

  .close-btn {
    padding: 0.5rem 1.25rem;
    font-size: 0.875rem;
    font-weight: 500;
    background: linear-gradient(135deg, var(--color-primary-500), var(--color-secondary-500));
    border: none;
    border-radius: 0.5rem;
    color: white;
    cursor: pointer;
    transition: all var(--timing-fast) var(--easing-default);
  }

  .close-btn:hover {
    transform: translateY(-1px);
    box-shadow: 0 4px 12px color-mix(in oklab, var(--color-primary-500) 30%, transparent);
  }

  /* ==========================================================================
     RESPONSIVE
     ========================================================================== */
  @media (max-width: 640px) {
    .info-card {
      padding: 1rem;
      border-radius: 0.875rem;
    }

    .info-title {
      font-size: 1.125rem;
    }

    .info-description {
      font-size: 0.875rem;
    }

    .accordion-trigger {
      padding: 0.75rem;
      font-size: 0.875rem;
    }

    .accordion-panel {
      padding: 0.875rem 1rem;
    }

    .prompt-modal {
      max-height: 95vh;
      border-radius: 0.875rem;
    }

    .prompt-modal-header {
      padding: 1rem;
    }

    .prompt-modal-body {
      padding: 1rem;
    }
  }

  /* ==========================================================================
     REDUCED MOTION
     ========================================================================== */
  @media (prefers-reduced-motion: reduce) {
    .accordion-trigger,
    .model-card,
    .prompt-btn,
    .modal-close-btn,
    .close-btn,
    .prompt-modal,
    .prompt-modal-backdrop {
      transition: none;
      animation: none;
    }

    .accordion-panel {
      animation: none;
    }
  }
</style>