<script lang="ts">
  import { t, currentLanguage } from '$lib/i18n';
  
  // Define the type for open sections as an array of strings
  let openSections = $state<string[]>([]);
  
  // State for the prompt modal
  let showPromptModal = $state(false);
  
  // Function to handle modal keyboard events
  function handleModalKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      showPromptModal = false;
    }
  }
</script>

<div class="card variant-glass p-4">
  <h2 class="h3 mb-3 text-white">{$t.analysis.title}</h2>
  
  <p class="mb-4 text-white">
    {$t.analysis.methodology} 
    <a href="https://islam.zmo.de/s/westafrica/" target="_blank" rel="noopener noreferrer" class="text-blue-300 hover:text-blue-200 underline" style="cursor: pointer !important;">
      {#if $currentLanguage === 'en'}
        <em>Islam West Africa Collection</em> (IWAC)
      {:else}
        <em>Collection Islam Afrique de l'Ouest</em> (<em>Islam West Africa Collection</em>, IWAC)
      {/if}
    </a>, 
    {$currentLanguage === 'en' ? 'a collaborative and open-access digital database developed by' : 'une base de données numérique collaborative et en libre accès développée par'} 
    <a href="https://www.frederickmadore.com/" target="_blank" rel="noopener noreferrer" class="text-blue-300 hover:text-blue-200 underline" style="cursor: pointer !important;">Frédérick Madore</a>. 
    {$currentLanguage === 'en' ? 'The results were generated by a large language model (LLM) guided by a prompt specifically designed for this task. Each article was analyzed according to three complementary dimensions, whose methodological details and limitations are presented below:' : 'Les résultats ont été générés par un grand modèle de langage (LLM) guidé par un prompt spécifiquement conçu pour cette tâche. Chaque article a été analysé selon trois dimensions complémentaires, dont les détails méthodologiques et les limites sont présentés ci-dessous :'}
  </p>
  
  <div class="accordion">
    <div class="accordion-item">
      <h3 class="h5">
        <button class="accordion-header" onclick={() => openSections = openSections.includes('polarite') ? openSections.filter(s => s !== 'polarite') : [...openSections, 'polarite']}>
          {$t.analysis.polaritySection}
        </button>
      </h3>
      {#if openSections.includes('polarite')}
        <div class="accordion-content p-3">
          <p class="mb-2">{$t.analysis.polarityDescription}</p>
          <ul class="list-disc ml-5 space-y-1">
            <li><span class="chip variant-filled-success">{$t.sentiment.veryPositive}</span> - {$t.analysis.veryPositiveDesc}</li>
            <li><span class="chip variant-soft-success">{$t.sentiment.positive}</span> - {$t.analysis.positiveDesc}</li>
            <li><span class="chip variant-soft-primary">{$t.sentiment.neutral}</span> - {$t.analysis.neutralDesc}</li>
            <li><span class="chip variant-soft-error">{$t.sentiment.negative}</span> - {$t.analysis.negativeDesc}</li>
            <li><span class="chip variant-filled-error">{$t.sentiment.veryNegative}</span> - {$t.analysis.veryNegativeDesc}</li>
            <li><span class="chip variant-ghost">{$t.sentiment.notApplicable}</span> - {$t.analysis.notApplicableNote}</li>
          </ul>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3 class="h5">
        <button class="accordion-header" onclick={() => openSections = openSections.includes('subjectivite') ? openSections.filter(s => s !== 'subjectivite') : [...openSections, 'subjectivite']}>
          {$t.analysis.subjectivitySection}
        </button>
      </h3>
      {#if openSections.includes('subjectivite')}
        <div class="accordion-content p-3">
          <p class="mb-2">{$t.analysis.subjectivityDescription}</p>
          <ul class="list-disc ml-5 space-y-1">
            <li><span class="chip variant-filled-success">1</span> <strong>{$t.subjectivity.factual}</strong> - {$t.analysis.factualDesc}</li>
            <li><span class="chip variant-soft-success">2</span> <strong>{$t.subjectivity.ratherFactual}</strong> - {$t.analysis.ratherFactualDesc}</li>
            <li><span class="chip variant-soft-primary">3</span> <strong>{$t.subjectivity.mixed}</strong> - {$t.analysis.mixedDesc}</li>
            <li><span class="chip variant-soft-error">4</span> <strong>{$t.subjectivity.ratherSubjective}</strong> - {$t.analysis.ratherSubjectiveDesc}</li>
            <li><span class="chip variant-filled-error">5</span> <strong>{$t.subjectivity.subjective}</strong> - {$t.analysis.subjectiveDesc}</li>
          </ul>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3 class="h5">
        <button class="accordion-header" onclick={() => openSections = openSections.includes('centralite') ? openSections.filter(s => s !== 'centralite') : [...openSections, 'centralite']}>
          {$t.analysis.centralitySection}
        </button>
      </h3>
      {#if openSections.includes('centralite')}
        <div class="accordion-content p-3">
          <p class="mb-2">{$t.analysis.centralityDescription}</p>
          <ul class="list-disc ml-5 space-y-1">
            <li><span class="chip variant-filled-tertiary">{$t.centrality.veryCentral}</span> {$t.analysis.veryCentralDesc}</li>
            <li><span class="chip variant-soft-tertiary">{$t.centrality.central}</span> {$t.analysis.centralDesc}</li>
            <li><span class="chip variant-soft-surface">{$t.centrality.secondary}</span> {$t.analysis.secondaryDesc}</li>
            <li><span class="chip variant-ghost">{$t.centrality.marginal}</span> {$t.analysis.marginalDesc}</li>
            <li><span class="chip variant-ghost">{$t.centrality.notAddressed}</span> {$t.analysis.notAddressedDesc}</li>
          </ul>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3 class="h5">
        <button class="accordion-header" onclick={() => openSections = openSections.includes('methodologie') ? openSections.filter(s => s !== 'methodologie') : [...openSections, 'methodologie']}>
          {$t.analysis.methodologyAiModel}
        </button>
      </h3>
      {#if openSections.includes('methodologie')}
        <div class="accordion-content p-3">
          <div class="space-y-4">
            <div>
              <h4 class="h6 mb-2 text-white font-semibold">{$t.analysis.modelUsed}</h4>
              <p class="mb-2 text-white">{$t.analysis.modelDescription} <a href="https://cloud.google.com/vertex-ai/generative-ai/docs/models/gemini/2-5-flash" target="_blank" rel="noopener noreferrer" class="text-blue-300 hover:text-blue-200 underline" style="cursor: pointer !important;"><span class="chip variant-soft-secondary">Gemini 2.5 Flash</span></a>{$t.analysis.modelDetails}</p>
            </div>
            
            <div>
              <h4 class="h6 mb-2 text-white font-semibold">{$t.analysis.technicalConfiguration}</h4>
              <ul class="list-disc ml-5 space-y-1 text-white text-sm">
                <li>{$t.analysis.temperatureConfig}</li>
                <li>{$t.analysis.outputFormat}</li>
                <li>{$t.analysis.cacheSystem}</li>
                <li>{$t.analysis.errorHandling}</li>
              </ul>
            </div>
            
            <div>
              <h4 class="h6 mb-2 text-white font-semibold">{$t.analysis.analysisPrompt}</h4>
              <p class="mb-2 text-white text-sm">{$t.analysis.promptDescription}</p>
              <ul class="list-disc ml-5 space-y-1 text-white text-sm">
                <li>{$t.analysis.promptFeature1}</li>
                <li>{$t.analysis.promptFeature2}</li>
                <li>{$t.analysis.promptFeature3}</li>
                <li>{$t.analysis.promptFeature4}</li>
                <li>{$t.analysis.promptFeature5}</li>
              </ul>
              <button 
                class="btn variant-soft-primary mt-3 text-sm"
                onclick={() => showPromptModal = true}
              >
                {$t.analysis.viewFullPrompt}
              </button>
            </div>
          </div>
        </div>
      {/if}
    </div>
    
    <div class="accordion-item">
      <h3 class="h5">
        <button class="accordion-header" onclick={() => openSections = openSections.includes('limites') ? openSections.filter(s => s !== 'limites') : [...openSections, 'limites']}>
          {$t.analysis.limitationsTitle}
        </button>
      </h3>
      {#if openSections.includes('limites')}
        <div class="accordion-content p-3">
          <p class="text-white">{$t.analysis.limitationsDescription}</p>
        </div>
      {/if}
    </div>
  </div>
</div>

<!-- Modal for displaying the complete prompt -->
{#if showPromptModal}
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <div 
    class="modal-backdrop" 
    role="dialog" 
    aria-modal="true" 
    aria-labelledby="prompt-modal-title"
    onclick={() => showPromptModal = false}
    onkeydown={handleModalKeydown}
    tabindex="-1"
  >
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <div 
      class="modal-content" 
      role="document"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
    >
      <div class="modal-header">
        <h3 id="prompt-modal-title" class="h3 text-white">{$currentLanguage === 'en' ? 'Complete Analysis Prompt' : 'Prompt d\'analyse complet'}</h3>
        <button 
          class="btn-close" 
          onclick={() => showPromptModal = false}
          aria-label={$currentLanguage === 'en' ? 'Close modal' : 'Fermer la modal'}
          type="button"
        >
          ✕
        </button>
      </div>
      
      <div class="modal-body">
        {#if $currentLanguage === 'en'}
          <div class="translation-notice mb-4 p-3 bg-yellow-900/20 border border-yellow-500/30 rounded-lg">
            <p class="text-yellow-200 text-sm">
              <strong>Note:</strong> This is a translation of the original French prompt used for the analysis. 
              The AI model received instructions in French as the corpus consists of French-language articles.
            </p>
          </div>
        {/if}
        
        <div class="prompt-container">
          <pre class="prompt-text">{$currentLanguage === 'en' ? 
            `You are an expert in sentiment analysis, specialized in studying representations of Islam and Muslims in the media, particularly in Francophone West Africa. Your task is to analyze the provided text from this specific angle and return a structured JSON analysis.

Your analysis must specifically evaluate how Islam and/or Muslims are depicted or represented in the article. Subjectivity and polarity should be judged in relation to this representation. If Islam and Muslims are only a marginal or irrelevant subject in the article, indicate this clearly.

For the following article text:
---
{article_text}
---

Please provide the following information in JSON format respecting the Pydantic SentimentAnalysisOutput schema:
{
  "centralite_islam_musulmans": "<Very central | Central | Secondary | Marginal | Not addressed>",
  "centralite_justification": "<Short justification (1 sentence) explaining the level of centrality of Islam/Muslims in the article>",
  "subjectivite_score": <score_from_1_to_5_or_null_if_not_addressed>,
  "subjectivite_justification": "<justification_in_1_2_sentences explaining why this subjectivity score was assigned regarding how the article treats Islam and/or Muslims, or 'Not applicable if the subject is not addressed'>",
  "polarite": "<Very positive | Positive | Neutral | Negative | Very negative | Not applicable>",
  "polarite_justification": "<justification_in_1_2_sentences explaining why this polarity was assigned regarding the portrayal of Islam and/or Muslims in the article, or 'Not applicable if the subject is not addressed'>"
}

Here are the scales to use:

Centrality of Islam and Muslims in the article:
- Very central: The article is mainly or entirely devoted to Islam and/or Muslims.
- Central: Islam and/or Muslims are one of the main subjects of the article.
- Secondary: Islam and/or Muslims are mentioned or discussed but do not constitute the main focus of the article.
- Marginal: Islam and/or Muslims are briefly mentioned anecdotally or peripherally.
- Not addressed: The article does not deal with Islam or Muslims at all.

Subjectivity (score from 1 to 5) – Evaluate the degree of objectivity/subjectivity of the article IN ITS WAY OF REPRESENTING Islam and/or Muslims (Assign 'null' if 'Not addressed' for centrality):
1: Very objective (reports verifiable facts about Islam/Muslims without expressing personal opinions or feelings about them, purely informative style on this theme).
2: Rather objective (mainly factual concerning Islam/Muslims, but may contain subtle traces of opinions or word choices suggesting a limited perspective on this theme).
3: Mixed (contains a balanced mix of facts and personal opinions/feelings concerning Islam/Muslims, or presents multiple viewpoints on this theme).
4: Rather subjective (clearly expresses opinions, feelings, or judgments about Islam/Muslims, even if based on some facts to support them).
5: Very subjective (heavily biased in its representation of Islam/Muslims, expresses intense opinions and emotions about them, with little or no objective presentation of facts, editorial or opinion piece style on this theme).

Polarity – Evaluate the general sentiment expressed IN THE ARTICLE TOWARDS Islam and/or Muslims, or concerning their representation (Assign 'Not applicable' if 'Not addressed' for centrality):
- Very positive: The portrayal of Islam/Muslims is extremely favorable, enthusiastic, laudatory.
- Positive: The portrayal of Islam/Muslims is favorable, optimistic.
- Neutral: No clear sentiment towards Islam/Muslims or balance between positive and negative aspects in their representation; factual tone without marked emotional charge towards them.
- Negative: The portrayal of Islam/Muslims is unfavorable, critical, pessimistic.
- Very negative: The portrayal of Islam/Muslims is extremely unfavorable, alarmist, very critical.

If centrality is "Not addressed", the "subjectivite_score" must be null, and "polarite", "subjectivite_justification", and "polarite_justification" must be "Not applicable". The JSON must always be valid.
For example, if "centralite_islam_musulmans" is "Not addressed":
{
  "centralite_islam_musulmans": "Not addressed",
  "centralite_justification": "The article mentions neither Islam nor Muslims.",
  "subjectivite_score": null,
  "subjectivite_justification": "Not applicable as the subject is not addressed.",
  "polarite": "Not applicable",
  "polarite_justification": "Not applicable as the subject is not addressed."
}

Make sure your response is only the requested structured JSON, without additional text or formatting before or after the JSON.` 
            : 
            `Vous êtes un expert en analyse de sentiments, spécialisé dans l'étude des représentations de l'islam et des musulmans dans les médias, notamment en Afrique de l'Ouest francophone. Votre tâche est d'analyser le texte fourni sous cet angle spécifique et de renvoyer une analyse structurée en JSON.

Votre analyse doit spécifiquement évaluer comment l'islam et/ou les musulmans sont dépeints ou représentés dans l'article. La subjectivité et la polarité doivent être jugées par rapport à cette représentation. Si l'islam et les musulmans ne sont qu'un sujet marginal ou non pertinent dans l'article, indiquez-le clairement.

Pour le texte de l'article suivant :
---
{article_text}
---

Veuillez fournir les informations suivantes au format JSON respectant le schéma Pydantic SentimentAnalysisOutput:
{
  "centralite_islam_musulmans": "<Très central | Central | Secondaire | Marginal | Non abordé>",
  "centralite_justification": "<Courte justification (1 phrase) expliquant le niveau de centralité de l'islam/des musulmans dans l'article>",
  "subjectivite_score": <score_de_1_a_5_ou_null_si_non_aborde>,
  "subjectivite_justification": "<justification_en_1_2_phrases expliquant pourquoi ce score de subjectivité a été attribué concernant la manière dont l'article traite de l'islam et/ou des musulmans, ou 'Non applicable si le sujet n'est pas abordé'>",
  "polarite": "<Très positif | Positif | Neutre | Négatif | Très négatif | Non applicable>",
  "polarite_justification": "<justification_en_1_2_phrases expliquant pourquoi cette polarité a été attribuée en ce qui concerne le portrait de l'islam et/ou des musulmans dans l'article, ou 'Non applicable si le sujet n'est pas abordé'>"
}

Voici les barèmes à utiliser :

Centralité de l'islam et des musulmans dans l'article :
- Très central : L'article est principalement ou entièrement consacré à l'islam et/ou aux musulmans.
- Central : L'islam et/ou les musulmans sont un des sujets principaux de l'article.
- Secondaire : L'islam et/ou les musulmans sont mentionnés ou discutés, mais ne constituent pas le focus principal de l'article.
- Marginal : L'islam et/ou les musulmans sont brièvement mentionnés de manière anecdotique ou périphérique.
- Non abordé : L'article ne traite pas du tout de l'islam ou des musulmans.

Subjectivité (note de 1 à 5) – Évaluez le degré d'objectivité/subjectivité de l'article DANS SA MANIÈRE DE REPRÉSENTER l'islam et/ou les musulmans (Attribuez 'null' si 'Non abordé' pour la centralité) :
1 : Très objectif (rapporte des faits vérifiables sur l'islam/les musulmans sans exprimer d'opinions ou de sentiments personnels à leur sujet, style purement informatif sur ce thème).
2 : Plutôt objectif (principalement factuel concernant l'islam/les musulmans, mais peut contenir des traces subtiles d'opinions ou des choix de mots suggérant une perspective limitée sur ce thème).
3 : Mixte (contient un mélange équilibré de faits et d'opinions/sentiments personnels concernant l'islam/les musulmans, ou présente plusieurs points de vue sur ce thème).
4 : Plutôt subjectif (exprime clairement des opinions, des sentiments ou des jugements sur l'islam/les musulmans, même s'il s'appuie sur certains faits pour les étayer).
5 : Très subjectif (fortement biaisé dans sa représentation de l'islam/des musulmans, exprime des opinions et des émotions intenses à leur sujet, avec peu ou pas de présentation objective des faits, style éditorial ou billet d'humeur sur ce thème).

Polarité – Évaluez le sentiment général exprimé DANS L'ARTICLE ENVERS l'islam et/ou les musulmans, ou concernant leur représentation (Attribuez 'Non applicable' si 'Non abordé' pour la centralité) :
- Très positif : Le portrait de l'islam/des musulmans est extrêmement favorable, enthousiaste, élogieux.
- Positif : Le portrait de l'islam/des musulmans est favorable, optimiste.
- Neutre : Pas de sentiment clair envers l'islam/des musulmans ou équilibre entre aspects positifs et négatifs dans leur représentation ; ton factuel sans charge émotionnelle marquée à leur égard.
- Négatif : Le portrait de l'islam/des musulmans est défavorable, critique, pessimiste.
- Très négatif : Le portrait de l'islam/des musulmans est extrêmement défavorable, alarmiste, très critique.

Si la centralité est "Non abordé", le "subjectivite_score" doit être null, et "polarite", "subjectivite_justification", et "polarite_justification" doivent être "Non applicable". Le JSON doit toujours être valide.
Par exemple, si "centralite_islam_musulmans" est "Non abordé":
{
  "centralite_islam_musulmans": "Non abordé",
  "centralite_justification": "L'article ne mentionne ni l'islam ni les musulmans.",
  "subjectivite_score": null,
  "subjectivite_justification": "Non applicable car le sujet n'est pas abordé.",
  "polarite": "Non applicable",
  "polarite_justification": "Non applicable car le sujet n'est pas abordé."
}

Assurez-vous que votre réponse est uniquement le JSON structuré demandé, sans texte ou formatage supplémentaire avant ou après le JSON.`}</pre>
        </div>
      </div>
      
      <div class="modal-footer">
        <button 
          class="btn variant-filled-primary" 
          onclick={() => showPromptModal = false}
          type="button"
        >
          {$t.common.close}
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .chip {
    padding: 0.25rem 0.5rem;
    font-size: 0.75rem;
    border-radius: 9999px;
    display: inline-block;
    background: var(--glass-bg);
    backdrop-filter: blur(8px);
    border: 1px solid var(--glass-border);
    transition: all var(--transition-fast);
  }
  
  .accordion {
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: var(--radius-lg);
    overflow: hidden;
    background: var(--glass-bg);
    backdrop-filter: blur(16px);
  }
  
  .accordion-item {
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  }
  
  .accordion-item:last-child {
    border-bottom: none;
  }
  
  .accordion-header {
    width: 100%;
    text-align: left;
    padding: 0.75rem 1rem;
    background: rgba(255, 255, 255, 0.05);
    color: white;
    cursor: pointer;
    transition: all var(--transition-normal);
    border: none;
    font-size: inherit;
    font-family: inherit;
  }
  
  .accordion-header:hover {
    background: rgba(255, 255, 255, 0.1);
    transform: translateX(4px);
  }
  
  .accordion-content {
    background: rgba(0, 0, 0, 0.2);
    color: white;
    backdrop-filter: blur(8px);
  }
  
  .h6 {
    font-size: 0.875rem;
    font-weight: 600;
    color: rgba(255, 255, 255, 0.9);
  }
  
  .translation-notice {
    background: rgba(180, 83, 9, 0.2);
    border: 1px solid rgba(245, 158, 11, 0.3);
    border-radius: 0.5rem;
  }
  
  /* Modal styles */
  .modal-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.8);
    backdrop-filter: blur(4px);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    padding: 1rem;
  }
  
  .modal-content {
    background: rgba(15, 23, 42, 0.95);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: var(--radius-xl);
    max-width: 90vw;
    max-height: 90vh;
    width: 800px;
    display: flex;
    flex-direction: column;
    backdrop-filter: blur(20px);
    box-shadow: var(--shadow-2xl);
  }
  
  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.5rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    background: var(--glass-bg);
    backdrop-filter: blur(8px);
  }
  
  .btn-close {
    background: var(--glass-bg);
    border: 1px solid var(--glass-border);
    color: white;
    font-size: 1.5rem;
    cursor: pointer;
    padding: 0.25rem;
    border-radius: var(--radius-md);
    transition: all var(--transition-normal);
    width: 2rem;
    height: 2rem;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .btn-close:hover {
    background: var(--glass-hover-bg);
    border-color: var(--glass-hover-border);
    transform: translateY(-1px);
  }
  
  .modal-body {
    flex: 1;
    overflow-y: auto;
    padding: 1.5rem;
  }
  
  .modal-footer {
    padding: 1.5rem;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    justify-content: flex-end;
  }
  
  .prompt-container {
    background: rgba(0, 0, 0, 0.3);
    border-radius: var(--radius-md);
    padding: 1rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
    backdrop-filter: blur(8px);
  }
  
  .prompt-text {
    color: #e2e8f0;
    font-family: 'Courier New', monospace;
    font-size: 0.875rem;
    line-height: 1.5;
    white-space: pre-wrap;
    word-wrap: break-word;
    margin: 0;
  }
  
  .btn {
    padding: 0.5rem 1rem;
    border-radius: var(--radius-md);
    border: none;
    cursor: pointer;
    font-weight: 500;
    transition: all var(--transition-normal);
    background: var(--glass-bg);
    backdrop-filter: blur(8px);
    border: 1px solid var(--glass-border);
  }
  
  .variant-soft-primary {
    background: rgba(59, 130, 246, 0.2);
    color: #93c5fd;
    border: 1px solid rgba(59, 130, 246, 0.3);
  }
  
  .variant-soft-primary:hover {
    background: rgba(59, 130, 246, 0.3);
    transform: translateY(-1px);
    box-shadow: var(--shadow-md);
  }
  
  .variant-filled-primary {
    background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary));
    color: white;
    border: none;
  }
  
  .variant-filled-primary:hover {
    background: linear-gradient(135deg, #2563EB, #7C3AED);
    transform: translateY(-1px);
    box-shadow: var(--shadow-lg);
  }
</style>