<!--
  SEOHead Component

  Emits per-view <head> metadata (title, description, keywords, Open Graph,
  Twitter card, canonical URL) plus the document's `lang`. All copy comes from
  the i18n catalog's `meta` namespace — no parallel hand-rolled translations
  here.

  `app.html` deliberately declares none of this: its markup lands before
  %sveltekit.head%, and a crawler takes the first title or og property it
  meets, so a static copy there would outrank everything below.
-->
<script lang="ts">
	import { t, currentLanguage } from '$lib/i18n';

	let { view = 'charts', comparisonMode = false }: { view?: string; comparisonMode?: boolean } =
		$props();

	const author = {
		name: 'Frédérick Madore',
		url: 'https://www.frederickmadore.com/'
	};
	const baseUrl = 'https://iwac.frederickmadore.com/sentiment-analysis/';
	// 1280x640 card generated by `scripts/social-preview.py` from the shipped
	// data. Regenerate it after a data refresh; the figures on it are real.
	const ogImage = `${baseUrl}social-preview.png`;

	type ViewMeta = { title: string; description: string; keywords: string };

	const metaContent = $derived.by(() => {
		const m = $t.meta;
		const lang = $currentLanguage;
		const url = `${baseUrl}?view=${view}${comparisonMode ? '&compare=true' : ''}&lang=${lang}`;
		const locale = lang === 'en' ? 'en_US' : 'fr_FR';
		const localeAlternate = lang === 'en' ? 'fr_FR' : 'en_US';

		const views = m.views as Record<string, ViewMeta>;

		// Comparison mode is switched on for the arbiter view as well as the
		// comparison one, because both work in terms of a model pair — so testing
		// the flag alone gave every arbiter page the comparison view's title and
		// description, and left `meta.views.arbiter` unreachable.
		if (comparisonMode && view !== 'arbiter') {
			return {
				title: `${m.comparisonTitle} - ${m.siteTitle}`,
				description: m.comparisonDescription,
				keywords: m.comparisonKeywords,
				url,
				locale,
				localeAlternate
			};
		}

		const viewMeta = views[view] ?? m.views.default;
		return {
			title: `${viewMeta.title} - ${m.siteTitle}`,
			description: `${m.viewDescriptionPrefix}${viewMeta.description}${m.viewDescriptionSuffix}`,
			keywords: `${viewMeta.keywords}, ${m.baseKeywords}`,
			url,
			locale,
			localeAlternate
		};
	});

	// The prerendered shell ships `lang="fr"` from app.html, which is only right
	// until someone picks English — a screen reader would then read English copy
	// with French pronunciation. `<svelte:html>` would express this declaratively
	// but is not a valid tag in this Svelte version, so set it on hydration and
	// on every switch. Effects are client-only, so the prerendered default holds.
	$effect(() => {
		document.documentElement.lang = $currentLanguage;
	});

	/**
	 * Marks every tag this component owns, so the sweep below can find them
	 * without a hand-maintained selector list that would silently fall out of
	 * date the first time a tag is added.
	 */
	const SEO_TAG = { 'data-seo-head': '' };

	// Hydration does not claim the prerendered <meta>/<link> elements: it appends
	// a fresh, live set and leaves the server-rendered one orphaned, so every tag
	// here ends up in the document twice. `<title>` is special-cased by Svelte and
	// is the one exception. Scrapers only ever read the served HTML, which holds a
	// single correct set, but a JS-executing crawler sees both — and two canonical
	// URLs that disagree once the visitor's language differs from the prerendered
	// default is the part that actually costs something.
	//
	// So drop the stale copies, keeping the LAST of each tag: Svelte appends the
	// live set after the server-rendered one. That ordering is the load-bearing
	// assumption. Identity also assumes each tag appears once — a second
	// og:locale:alternate, were a third language ever added, would need a key
	// that folds in the content.
	$effect(() => {
		// Touch the metadata so a tag that starts duplicating later is caught too.
		void metaContent;

		const owned = [...document.head.querySelectorAll('[data-seo-head]')];
		// The tag name is part of the identity: <meta name="author"> and
		// <link rel="author"> would otherwise collide and eat each other.
		const identify = (el: Element) =>
			`${el.tagName}:${el.getAttribute('name') ?? el.getAttribute('property') ?? el.getAttribute('rel')}`;

		for (const [i, el] of owned.entries()) {
			const key = identify(el);
			if (owned.slice(i + 1).some((later) => identify(later) === key)) el.remove();
		}
	});
</script>

<svelte:head>
	<title>{metaContent.title}</title>
	<meta {...SEO_TAG} name="description" content={metaContent.description} />
	<meta {...SEO_TAG} name="keywords" content={metaContent.keywords} />
	<meta {...SEO_TAG} name="author" content={author.name} />
	<meta {...SEO_TAG} name="robots" content="index, follow" />

	<!-- Open Graph -->
	<meta {...SEO_TAG} property="og:type" content="website" />
	<meta {...SEO_TAG} property="og:site_name" content="IWAC Sentiment Analysis" />
	<meta {...SEO_TAG} property="og:title" content={metaContent.title} />
	<meta {...SEO_TAG} property="og:description" content={metaContent.description} />
	<meta {...SEO_TAG} property="og:url" content={metaContent.url} />
	<meta {...SEO_TAG} property="og:image" content={ogImage} />
	<meta {...SEO_TAG} property="og:image:width" content="1280" />
	<meta {...SEO_TAG} property="og:image:height" content="640" />
	<meta {...SEO_TAG} property="og:image:alt" content={$t.meta.ogImageAlt} />
	<meta {...SEO_TAG} property="og:locale" content={metaContent.locale} />
	<meta {...SEO_TAG} property="og:locale:alternate" content={metaContent.localeAlternate} />

	<!-- Twitter Card -->
	<meta {...SEO_TAG} name="twitter:card" content="summary_large_image" />
	<meta {...SEO_TAG} name="twitter:title" content={metaContent.title} />
	<meta {...SEO_TAG} name="twitter:description" content={metaContent.description} />
	<meta {...SEO_TAG} name="twitter:image" content={ogImage} />

	<!-- Canonical URL -->
	<link {...SEO_TAG} rel="canonical" href={metaContent.url} />
	<link {...SEO_TAG} rel="author" href={author.url} />
</svelte:head>
